version: "3.8"
services:
    umerx_blackdog_configurator_backend:
        image: ghcr.io/umerx-github/blackdog-configurator-backend:latest
        restart: always
        depends_on:
            - db
        environment:
            - NODE_ENV=${BLACKDOG_CONFIGURATOR_BACKEND_NODE_ENV}
            - BLACKDOG_CONFIGURATOR_BACKEND_DB_HOSTNAME=${BLACKDOG_CONFIGURATOR_BACKEND_DB_HOSTNAME}
            - BLACKDOG_CONFIGURATOR_BACKEND_DB_NAME=${BLACKDOG_CONFIGURATOR_BACKEND_DB_NAME}
            - BLACKDOG_CONFIGURATOR_BACKEND_DB_USER=${BLACKDOG_CONFIGURATOR_BACKEND_DB_USER}
            - BLACKDOG_CONFIGURATOR_BACKEND_DB_PASSWORD=${BLACKDOG_CONFIGURATOR_BACKEND_DB_PASSWORD}
    umerx_blackdog_trader_typescript:
        image: ghcr.io/umerx-github/blackdog-trader-typescript:latest
        restart: always
        depends_on:
            - umerx_blackdog_configurator_backend
        environment:
            - BLACKDOG_CONFIGURATOR_BACKEND_SCHEME=${BLACKDOG_CONFIGURATOR_BACKEND_SCHEME}
            - BLACKDOG_CONFIGURATOR_BACKEND_HOST=${BLACKDOG_CONFIGURATOR_BACKEND_HOST}
            - BLACKDOG_CONFIGURATOR_BACKEND_PORT=${BLACKDOG_CONFIGURATOR_BACKEND_PORT}
            - BLACKDOG_CONFIGURATOR_BACKEND_PATH=${BLACKDOG_CONFIGURATOR_BACKEND_PATH}
    db:
        image: mysql:latest
        restart: always
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${BLACKDOG_CONFIGURATOR_BACKEND_DB_PASSWORD}
            MYSQL_DATABASE: ${BLACKDOG_CONFIGURATOR_BACKEND_DB_NAME}
            MYSQL_USER: ${BLACKDOG_CONFIGURATOR_BACKEND_DB_USER}
            MYSQL_PASSWORD: ${BLACKDOG_CONFIGURATOR_BACKEND_DB_PASSWORD}
volumes:
    db_data:
