version: "3.8"
services:
    umerx_blackdog_configurator_frontend:
        image: ghcr.io/umerx-github/blackdog-configurator-frontend:latest
        restart: always
        depends_on:
            - umerx_blackdog_configurator_backend
        networks:
            - nginx_proxy_network
    umerx_blackdog_configurator_backend:
        image: ghcr.io/umerx-github/blackdog-configurator-backend:latest
        restart: always
        depends_on:
            - db
        networks:
            - nginx_proxy_network
            - default
        environment:
            - NODE_ENV=production
            - BLACKDOG_CONFIGURATOR_BACKEND_DB_HOSTNAME=db
            - BLACKDOG_CONFIGURATOR_BACKEND_DB_NAME=blackdog
            - BLACKDOG_CONFIGURATOR_BACKEND_DB_USER=blackdog
            - BLACKDOG_CONFIGURATOR_BACKEND_DB_PASSWORD=${BLACKDOG_CONFIGURATOR_BACKEND_DB_PASSWORD}
    umerx_blackdog_trader_typescript:
        image: ghcr.io/umerx-github/blackdog-trader-typescript:latest
        restart: always
        depends_on:
            - umerx_blackdog_configurator_backend
        networks:
            - default
        environment:
            - BLACKDOG_CONFIGURATOR_BACKEND_SCHEME=http
            - BLACKDOG_CONFIGURATOR_BACKEND_HOST=umerx_blackdog_configurator_backend
            - BLACKDOG_CONFIGURATOR_BACKEND_PORT=80
            - BLACKDOG_CONFIGURATOR_BACKEND_PATH=
    db:
        image: mysql:latest
        restart: always
        networks:
            - default
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${BLACKDOG_CONFIGURATOR_BACKEND_DB_ROOT_PASSWORD}
            MYSQL_DATABASE: blackdog
            MYSQL_USER: blackdog
            MYSQL_PASSWORD: ${BLACKDOG_CONFIGURATOR_BACKEND_DB_PASSWORD}
volumes:
    db_data:
networks:
    nginx_proxy_network:
        external: true
