version: "3.8"
services:
    umerx_blackdog_configurator_frontend:
        image: ghcr.io/umerx-github/blackdog-configurator-frontend:dev
        ports:
            - ${BLACKDOG_CONFIGURATOR_FRONTEND_HOST_PORT}:80
    umerx_blackdog_configurator_backend:
        ports:
            - 62452:80
    umerx_blackdog_trader_typescript:
        environment:
            - ALPACA_API_KEY=${ALPACA_API_KEY}
            - ALPACA_API_SECRET=${ALPACA_API_SECRET}
            - ALPACA_API_USE_TEST_CREDENTIALS=${ALPACA_API_USE_TEST_CREDENTIALS}
    adminer:
        image: adminer
        depends_on:
            - db
        restart: always
        ports:
            - ${BLACKDOG_CONFIGURATOR_BACKEND_ADMINER_HOST_PORT}:8080
